# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"



# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: [ ]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: docs/additional_requirements.txt
    - method: pip
      path: https://root-experimental-python-wheels.web.cern.ch/ROOT-0.1a5-cp39-cp39-manylinux_2_28_x86_64.whl#sha256=fb3c9c68a4e90d28106c660c2947b8364a18ce59689517a7f4819ab2c8acb40f
