# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev libxext-dev libxft-dev libxpm-dev python3 libtbb-dev libvdt-dev libgif-dev gfortran libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libfftw3-dev libcfitsio-dev libgraphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python3-dev python3-numpy libxml2-dev libkrb5-dev libgsl-dev qtwebengine5-dev nlohmann-json3-dev libmysqlclient-dev libgl2ps-dev liblzma-dev libxxhash-dev liblz4-dev libzstd-dev
  commands:
    - wget https://root.cern/download/root_v6.30.08.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz -O root.tar.gz
    - tar -xzf root.tar.gz
    - source root/bin/thisroot.sh

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: [ ]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: git+https://github.com/jiangyi15/tf-pwa
