name: unittests

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - develop
      - "release/*"
  pull_request:
  release:
    types:
      - published

defaults:
  run:
    # The login shell is necessary for the setup-micromamba setup
    # to work in subsequent jobs.
    # https://github.com/mamba-org/setup-micromamba#about-login-shells
    shell: bash -e -l {0}

jobs:
  tests_graph:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 150
    strategy:
      max-parallel: 16
      fail-fast: False
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.9", "3.12" ]
        jit: [ "0", "1" ]
    name: Tests for Python ${{ matrix.python-version }} with JIT=${{ matrix.jit }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        name: Set up Micromamba environment
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }} pip uv root
      - name: Install Python dependencies
        run: |
          which python
          python -V
          uv pip install -e ".[dev]"
      - name: Test with pytest
        run: |
          ZFIT_DO_JIT=${{ matrix.jit }}
          coverage run --source=. --omit=".tox/*" --branch -m pytest .
          coverage report
